name: Auto Publish to npm

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # supaya bisa lihat perubahan sebelumnya

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Check if version changed
        id: version_check
        run: |
          VERSION_CHANGED=$(git diff HEAD^ HEAD package.json | grep '"version"' || true)
          if [ -n "$VERSION_CHANGED" ]; then
            echo "Version changed. Will publish."
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No version change. Skipping publish."
            echo "changed=false" >> $GITHUB_OUTPUT

      - name: Publish to npm
        if: steps.version_check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
